import './global.css';

export const metadata = {
  title: 'Welcome to apps/insights-app',
  description: 'Generated by create-nx-workspace',
};

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
